export const BLOCKADDTASK = "BLOCKADDTASK";
export const HIDDENADDTASK = "HIDDENADDTASK";

export const BLOCKUPDATETASK = "BLOCKUPDATETASK";
export const HIDDENUPDATETASK = "HIDDENUPDATETASK";

export const BLOCKUPDATEPASSWORD = "BLOCKUPDATEPASSWORD";
export const HIDDENUPDATEPASSWORD = "HIDDENUPDATEPASSWORD";

export const BLOCKUPDATENAME = "BLOCKUPDATENAME";
export const HIDDENUPDATENAME = "HIDDENUPDATENAME";
